apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: your-pipeline-name
spec:
  params:
    - name: repo-url
      type: string
      description: The Git repository URL
    - name: revision
      type: string
      description: The Git revision (branch or tag) to build
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.revision)"

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: flake8
      params:
        - name: args
          value: "--max-line-length=120"
      runAfter:
        - clone

    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: nose
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"
      runAfter:
        - clone
